import type { Metadata } from "next";
import "./globals.css";
import ParticleConnectkit from "components/Connectkit";

import SideBar from "components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-hide">
      <body className="antialiased dark">
        <ParticleConnectkit>
          <SideBar />
          {children}
        </ParticleConnectkit>
      </body>
    </html>
  );
}
